//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurgeSolutions.FrontEnd {
    
    
    public partial class BlogItem {
        
        /// <summary>
        /// BlogDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SurgeSolutions.FrontEnd.UserControls.BlogDetails BlogDetails;
        
        /// <summary>
        /// Blogs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SurgeSolutions.FrontEnd.UserControls.BlogList Blogs;
    }
}
