//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurgeSolutions.FrontEnd {
    
    
    public partial class PropertyT {
        
        /// <summary>
        /// Slideshow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SurgeSolutions.FrontEnd.UserControls.SlideshowDB Slideshow;
        
        /// <summary>
        /// PropertySlides1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SurgeSolutions.FrontEnd.UserControls.PropertySlides PropertySlides1;
        
        /// <summary>
        /// PropertyFloorplan1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SurgeSolutions.FrontEnd.UserControls.PropertyFloorplan PropertyFloorplan1;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SurgeSolutions.FrontEnd.masterpages.Standard Master {
            get {
                return ((SurgeSolutions.FrontEnd.masterpages.Standard)(base.Master));
            }
        }
    }
}
